### ISSUE TITLE
Missing types

### ISSUE THREAD

**Issue by nandorojo** [shuding/stable-hash#4]
It would by nice if there were TS intellisense. Since the lib is so simple, we could use a basic `index.d.ts` file.

**Comment by nandorojo** [comment]
This will do in my repo for now: 

```ts
declare module 'stable-hash' {
  function stableHash(arg: any): string

  export = stableHash
}
```

<img width="764" alt="Screen Shot 2021-09-29 at 11 46 32 AM" src="https://user-images.githubusercontent.com/13172299/135303550-ca26a9db-c360-4431-b100-962e9785efcb.png">

**Comment by shuding** [comment]
Yeah we can include a simple `.d.ts` file there! 👍
